### ISSUE TITLE
Play directly

### ISSUE THREAD

**Issue by darkzbaron** [PCigales/DLNAPlayOn#1]

**Comment by PCigales** [comment]
Thank you for reporting an issue, but I am afraid I won't be able to fix anything if you don't provide me with a description of the problem, in particular the command you entered, what you intended to do, what went wrong, and ideally a log (use -v 2 option to maximize the verbosity). I can't guess otherwise the nature and the origin of the bug, if any.

**Comment by darkzbaron** [comment]
Hi there, I am still playing around and my message didn't get send but thanks so much for the quick response

**Comment by darkzbaron** [comment]
The issue is that when I run python PlayOn.py c "MusicFolder" --name "Speaker Name"  --verbosity=2

Sometimes it connects directly but sometimes I have to wait that the speaker appears then select it then play it. 

I am in the process of understanding the way socket works and I am planning to add the following commands after "Enregistrement du renderer SpeakerName"

socket.send("command=sel&index=0")
socket.send("Lecture")

I haven't tested that and I am actually planning to send these commands via another script cause I am not sure how to reuse your socket object in your script.

Any help is appreciated, thanks so much for the amazing work!


Not sure if that the best solution

**Comment by darkzbaron** [comment]
My idea is actually that when a speaker is selected one should not have to manually reselect it so it's a valid candidate idea for improvement!

**Comment by darkzbaron** [comment]
02/12/2021 21:27:13 : Démarrage du serveur d'écoute des publicités de périphérique DLNA
02/12/2021 21:27:13 : Démarrage du gestionnaire de contrôleur de lecture pour serveur d'interface Web
02/12/2021 21:27:13 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:27:13 : Réception d'une réponse au message de recherche de 172.22.160.1:1900
02/12/2021 21:27:13 : Réponse de 172.22.160.1:1900 ignorée en raison de la discordance d'adresse de l'URL de description
02/12/2021 21:27:13 : Démarrage du serveur d'interface Web
Appuyez sur "S" pour stopper
Appuyez sur "!" et "M" pour alterner entre les modes de remuxage (MP4, MPEGTS, !MP4, !MPEGTS) pour la prochaine session de lecture - mode actuel: MP4
Appuyez sur "T" pour alterner entre les types de serveur (auto, séquentiel, aléatoire) pour la prochaine session de lecture - mode actuel: auto
Appuyez sur "E" pour activer/désactiver la lecture en boucle - mode actuel: désactivé
02/12/2021 21:27:14 : Connexion de 192.168.1.154:7353
02/12/2021 21:27:14 : Réponse à l'interface de contrôle 192.168.1.154:7353
02/12/2021 21:27:15 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:27:15 : Réception d'une réponse au message de recherche de 172.22.160.1:1900
02/12/2021 21:27:15 : Réponse de 172.22.160.1:1900 ignorée en raison de la discordance d'adresse de l'URL de description
02/12/2021 21:27:18 : "GET / HTTP/1.1" 200 -
02/12/2021 21:27:19 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:27:19 : Réception d'une réponse au message de recherche de 172.22.160.1:1900
02/12/2021 21:27:19 : Réponse de 172.22.160.1:1900 ignorée en raison de la discordance d'adresse de l'URL de description
02/12/2021 21:27:25 : Réponse à l'interface de contrôle 192.168.1.154:7353
02/12/2021 21:27:26 : Interruption du gestionnaire de contrôleur de lecture pour serveur d'interface Web
02/12/2021 21:27:26 : Démarrage du gestionnaire d'affichage de renderer dans le formulaire de lancement pour serveur d'interface Web
02/12/2021 21:27:26 : Démarrage de la recherche de renderer DLNA
02/12/2021 21:27:26 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:27:26 : Envoi d'un message de recherche de server DLNA
02/12/2021 21:27:26 : Démarrage du serveur pour Websocket à l'adresse 192.168.1.154:8216
02/12/2021 21:27:26 : Réception d'une réponse au message de recherche de 172.22.160.1:1900
02/12/2021 21:27:26 : Réponse de 172.22.160.1:1900 ignorée en raison de la discordance d'adresse de l'URL de description
02/12/2021 21:27:26 : Réception d'une réponse au message de recherche de 172.22.160.1:1900
02/12/2021 21:27:26 : Réponse de 172.22.160.1:1900 ignorée en raison de la discordance d'adresse de l'URL de description
02/12/2021 21:27:26 : "GET / HTTP/1.1" 307 -
02/12/2021 21:27:26 : Réponse à l'interface de contrôle 192.168.1.154:7353
02/12/2021 21:27:26 : "GET /start.html HTTP/1.1" 200 -
02/12/2021 21:27:26 : WebSocket serveur 192.168.1.154:8216 -> demande de connexion du WebSocket 192.168.1.154:7396
02/12/2021 21:27:26 : WebSocket serveur 192.168.1.154:8216 -> connexion au WebSocket 192.168.1.154:7396
02/12/2021 21:27:26 : WebSocket serveur 192.168.1.154:8216 -> WebSocket 192.168.1.154:7396 -> envoi de la donnée end
02/12/2021 21:27:29 : Envoi d'un message de recherche de server DLNA
02/12/2021 21:27:29 : Réception d'une réponse au message de recherche de 172.22.160.1:1900
02/12/2021 21:27:29 : Réponse de 172.22.160.1:1900 ignorée en raison de la discordance d'adresse de l'URL de description
02/12/2021 21:28:01 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:28:01 : Réception d'une réponse au message de recherche de 172.22.160.1:1900
02/12/2021 21:28:01 : Réponse de 172.22.160.1:1900 ignorée en raison de la discordance d'adresse de l'URL de description
02/12/2021 21:28:36 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:29:11 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:29:46 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:29:46 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:29:46 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:29:46 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:29:47 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:29:47 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:29:47 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:30:22 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:30:23 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:30:23 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:30:23 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:30:24 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:30:24 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:30:24 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:30:57 : Envoi d'un message de recherche de renderer DLNA
02/12/2021 21:30:59 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:30:59 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:30:59 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:31:00 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:31:00 : Réception d'une réponse au message de recherche de 192.168.1.25:1900
02/12/2021 21:31:00 : Réception d'une réponse au message de recherche de 192.168.1.25:1900

**Comment by PCigales** [comment]
Thank you for all those informations, and also for your compliments !

I think that I understand what is happening: the renderer "Speaker Name" takes to much time to respond to the search requests sent by the script, and therefore, the timeout is reached and the interface switches to the page of selection of renderers.

To explain more thoroughly how things work in the UPnP / DLNA protocol:
- the DLNA controller  (which is how this script acts for) sends search messages of renderers using the SSDP discovery protocol, which relies on UDP multicast datagrams sent on 239.255.255.250:1900
- your switch / router casts these messages to all devices who suscribed through the IGMP protocol to this multicast group
- the devices that comply with the query conditions in the search messages send their response to the controller providing various information allowing the communication

What happens when the connection is not direct and that you are sent back to the renderer selection page is that the delay between the search message and the response is to long, greater than the allowed duration. It can either come from the switch / router or from the renderer. You can try, if you have another DLNA renderer such as a smart TV or a smartphone with an application such as BubbleUPnP, to check if the same issue occurs or not, to dertermine where the slowdown takes place.

This process is performed in "manage_control" at lines 4955 to 4968: a first discovery request is made with a timeout of 2 seconds, then, if it is not successfull, a second one with a timeout of 4s, and eventually, if the previous one also fails, with a timeout of 6s. If at the end of these trials, the requested renderer has not been found, the script switches to the renderer selection mode to allow the user to choose another available renderer or wait for the targeted renderer to be discovered. It is what you cas see in your log at "21:27:26 ", which occurs after the threee search requests at "21:27:13", "21:27:15" and "21:27:19" (2, 4 then 6 seconds apart).

So, you could increase the timeout at line 4959, or allow more attempts at line 4958 (by replacing "3" by a greater number, or looping endlessly).

As for your proposition of automatically select the renderer requested in the command when it is available, it is already the case. I have just tried with my TV and my phone: I launched the script asking for my phone but only turning on my TV, and after the 2 + 4 + 6 s, the renderer selection page was displayed, but when I then ran BubbleUPnP on my phone, the device was discovered and automatically selected, so I only had to click on "Lire" (I have to find the time to make translations into english !) to start the playback.

Please note, also, that the communication between the script and the browser uses the websocket protocol, so you cannot directly send a message such as "socket.send("command=sel&index=0")" (anyway you would have to encode the string to binary), as you have to go through the specific syntax of this procotol which is rather complicated, and implies that you first build data frames encapsulating the payload (see https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers if you are interested in, but if you are learning how sockets work, it is perhaps not the better use case to start with).

If you want the script to automatically launch the playback on the desired renderer when it is discovered, rather than only selecting it, you could try to add these instructions after line 4927:
  self.TargetStatus = DLNAWebInterfaceServer.INTERFACE_CONTROL
  self.RenderersDataStore.Message = 'redirect'
but I am not quite sure it will not have unexpected consequences, I have to dive into the code again as it is starting to date since I wrote this script, and the complexity makes that when you change something somewhere it can disturb elsewhere, so you have to be careful to avoid a regression or an annoying bug.
Feel free to test of course !

**Comment by darkzbaron** [comment]
That works, thanks so much! It's really the best DNLA player out there, it has everything! 
Also, as you saw in the log. one of the problem is this ip address "172.22.160.1:1900" which responds first and messes all up, 
I have added a line in the discover class to exclude IP addresses which don't start with 192.  Is there a way to exclude them in with the  SSDP discovery protocol ?

**Comment by PCigales** [comment]
I am glad for you that it worked.

You don't have to worry about the response from the device at 172.22.160.1: it does not mess the discovery process, and its response is rejected because it reports a different ip (in the "location" field, see above) compared to the ip of the socket it uses to send the message. That's for safety reason that I introduced this check, to prevent the script to establish a connexion to an url which may not be the one of the device which responded as the ip differs.

A response to a m-search SSDP message has this structure:
HTTP/1.1 200 OK
LOCATION: [URL of the device]
ST: [search target]
USN: [advertising identifier]

Unlike the TCP protocol, the UDP protocol used for SSDP does not imply any form of establishement of connexion nor handshake, so the fact that a device responds does not have any consequence for the ability of other devices to also have their own response taken into account, except if a mere saturation occurs, which is clearly not the case here.

That said, this ip does not belong to the same mask that the one starting with "192". It is also a private ip, but from another subnet, so it seems that the router is interfaced with at least two private networks (I even suspect that this ip is its own ip on this other sub network as it ends with "1").

I don't see any mean to programmatically exclude a range of IP from the SSDP process, as it is up to the router to determine to which devices it must send the multicasted datagrams (and as I indicated in the previous message, the subscriptions to multicast groups are managed through the IGMP protocol: https://en.wikipedia.org/wiki/Internet_Group_Management_Protocol).
The SSDP protocol only grants the possibility to indicate a "search target" in the "ST" header of the search message, but nothing prevents a device which does not fulfill this condition to respond, and besides, the range of supported criterion does not include the IP address.

**Comment by darkzbaron** [comment]
Ok thanks for the info that really helps me to get up to speed with network related issue in which in typically struggle. 

In addition to your fix after line 4927:
self.TargetStatus = DLNAWebInterfaceServer.INTERFACE_CONTROL
self.RenderersDataStore.Message = 'redirect'

I added this to start the playback directly before the line 5287
self.DLNARendererControlerInstance.send_Play(renderer)

Thanks so much for the quick reply, DNLA is awesome but somehow there are not so much good software around so thanks you again!

**Comment by PCigales** [comment]
> My idea is actually that when a speaker is selected one should not have to manually reselect it so it's a valid candidate idea for improvement!

New release (-o option)
