### ISSUE TITLE
Failure of the opening of "..." as "web page url"

### ISSUE THREAD

**Issue by ndevev** [PCigales/DLNAPlayOn#4]
I always get this error message "Failure of the opening of "..." as "web page url" for every url recently.
It worked well before.

**Comment by PCigales** [comment]
Could you please provide an url with which you get this error ? Also, did you check that the path in the first line of youtube-dl.bat matches with the executable ? Did you try an ancient release to see if the error message only occurs with the latest version ?
I ask you these questions because I used the app not later than yesterday to cast a video from internet to my tv without facing any issue.

**Comment by ndevev** [comment]
Now I get the latest version of the yt-dlp(2024.12.13) and put it to the youtube-dl.bat @set "youtube-dl_path=, and now it works well.
Thank you for the quick response.
